import { SchengenFormData } from "@/types/schengen";

export const SAMPLE_ISSUED_FORM: SchengenFormData = {
  field1_surname: "ELZOWEY",
  field2_surnameAtBirth: "ELZOWEY",
  field3_firstNames: "TAREK ABDALLAH",
  field4_dateOfBirth: "1989-05-14",
  field5_placeOfBirth: "Tripoli",
  field6_countryOfBirth: "Libya",
  field7_currentNationality: "Libya",
  field7_nationalityAtBirth: "Libya",
  field7_otherNationalities: "",
  field8_sex: "MALE",
  field9_civilStatus: "MARRIED",
  field9_civilStatusOther: "",
  field10_parentalAuthority: "",
  field11_nationalIdNumber: "11989051400321",
  field12_travelDocType: "ORDINARY",
  field12_travelDocTypeOther: "",
  field13_travelDocNumber: "LBY987654",
  field14_issueDate: "2024-03-20",
  field15_validUntil: "2029-03-19",
  field16_issuedBy: "Libya",
  field17_euFamilyMemberSurname: "",
  field17_euFamilyMemberFirstName: "",
  field17_euFamilyMemberDob: "",
  field17_euFamilyMemberNationality: "",
  field17_euFamilyMemberDocNumber: "",
  field17_euFamilyMemberRelationship: "",
  field18_homeAddress: "Omar Al-Mukhtar St, Hay Al-Andalus, Tripoli, Libya",
  field18_email: "tarek.elzowey@email.com",
  field18_phone: "+218 91 234 5678",
  field19_residenceInOtherCountry: "NO",
  field19_residencePermitNumber: "",
  field19_residencePermitValidUntil: "",
  field20_currentOccupation: "Software Engineer",
  field21_employerNameAndAddress: "Advanced Tech Co., Tripoli Tower, 10th Floor, Tripoli",
  field21_employerPhone: "+218 21 444 5566",
  field22_purposeOfJourney: ["TOURISM"],
  field22_purposeOther: "",
  field23_additionalInfoPurpose: "Holiday in Paris, 15 days, hotel prepaid.",
  field24_memberStateOfMainDestination: "FRANCE",
  field24_otherMemberStates: "",
  field25_memberStateOfFirstEntry: "FRANCE",
  field26_numberOfEntries: "SINGLE",
  field26_intendedArrivalDate: "2026-06-10",
  field26_intendedDepartureDate: "2026-06-25",
  field26_durationOfStayDays: "15",
  field27_fingerprintsCollectedPreviously: "NO",
  field27_fingerprintsDate: "",
  field27_visaStickerNumber: "",
  field28_entryPermitFinalDestination: "",
  field28_entryPermitIssuedBy: "",
  field28_entryPermitValidFrom: "",
  field28_entryPermitValidUntil: "",
  field29_invitingPersonOrHotelName: "Novotel Paris Centre Tour Eiffel",
  field29_hostAddressAndEmail: "61 Quai de Grenelle, 75015 Paris, France",
  field29_hostPhone: "+33 1 40 58 20 00",
  field30_invitingCompany: "",
  field30_companyContactPerson: "",
  field30_companyAddressAndPhone: "",
  field31_coveredBy: "APPLICANT",
  field31_applicantMeans: ["CASH", "CREDIT_CARD", "PREPAID_ACCOMMODATION"],
  field31_applicantMeansOther: "",
  field31_sponsorMeans: [],
  field31_sponsorMeansOther: "",
  field31_sponsorType: "",
  field32_placeAndDate: "Tripoli, 15-04-2026",
  field33_signatureName: "TAREK ABDALLAH ELZOWEY",
  field34_fillerName: "",
  field34_fillerAddressEmail: "",
  field34_fillerPhone: "",
};
